# vim ft=yaml
# travis-ci.org definition for simple-cython-example build
#

language: c
env:
    - PYTHON=python PYSUF='' PYVER=2.7
install:
    - sudo apt-get update  # needed for python3-numpy
    - sudo apt-get install $PYTHON-dev
    - sudo apt-get install $PYTHON-numpy
    - sudo apt-get install cython
    - sudo apt-get install $PYTHON-setuptools
    - sudo apt-get install $PYTHON-nose
    - $PYTHON setup.py build
    - sudo $PYTHON setup.py install
script:
    - nosetests-$PYVER